### ISSUE TITLE
Wrong folder name if new page starts with a number

### ISSUE THREAD

**Issue by distantnative** [getkirby-v2/panel#326] opened 2015-01-05 15:31 UTC
I'm building a blog with Kirby. When a new blog post (as a new page) is created in the panel and starts with a number (e.g. "2014 – what was and will be.") it is automatically interpreted as the order number (so the folder looks like `2014-what-was-and-will-be` instead `2-2014-what-was-and-will-be`.

**Comment by lukasbestle** [comment] 2015-01-05 15:37
Hmm, that's a difficult problem. Kirby (the core as well) sees that page and, as you wrote, interprets the number as sorting number. Automatically adding a sorting number when creating the page is not a solution though, because that would make every page visible by default.

What you could do is to manually set a URI without a number at the beginning when creating the page. Maybe, there's an even simpler solution how this could be fixed in the core, but I can't think of one. Do you have an idea?

**Comment by distantnative** [comment] 2015-01-05 15:41
Not really. Setting the URI without the number first works for me, I guess.

**Comment by lukasbestle** [comment] 2015-01-06 11:03
The problem is that it's not an actual bug. The Kirby semantics say that a number at the beginning of a page name is a sorting number. Even when not using the Panel, this makes this type of page name unusable, because it breaks visibility detection.

**Comment by distantnative** [comment] 2015-01-06 11:08
But I agree with ausminternet that the panel should throw a warning at least then.

**Comment by lukasbestle** [comment] 2015-01-06 11:10
Yeah, that's a good idea. Something like "this page will be visible right after creation, the number at the beginning won't be part of the URI" maybe?

**Comment by ausminternet** [comment] 2015-01-06 11:26
No, this would be a nice text for a developer using kirby, but not for a "normal user". And it is also impossible to make it invisible after that. Maybe the parser, which creates the URL-Appendix from the title on adding a subpage could strip leading numbers?

**Comment by lukasbestle** [comment] 2015-01-06 11:30
Ah, you mean the auto-generated URIs. Stripping numbers could work, but it could also be a bit confusing if the URI lacks the number you added to the title.

**Comment by servicethinker** [comment] 2015-01-17 23:11
I think it needs to be forbidden through the Panel. So an error message would be great. 

Maybe another solution: forgiving formats. Instead of throwing a big red error message against the user's head the Panel could give straight a solution for the problem and informs the user about it. Something like "Sorry, numbers are not allowed so we removed it. Is that okay?".

**Comment by lukasbestle** [comment] 2015-01-18 09:57
That could work. Since the field is an "enter an URI" field and URIs can't have numbers at the beginning, the Panel should actually not allow adding numbers.

**Comment by AhoyLemon** [comment] 2017-09-01 20:29
It's been quite a while on this issue, and I'd like to bring it up again since my client just started running into it. 

The client has pages called, for example `2x-tuesday` and `4th-of-july-spectacular` and `10k-fun-run` and it's not reasonable I'll be able to correctly describe that their slug structure is upsetting how the site works. I can of course change all these slugs, but I do think there needs to be a hook in the slug field that checks for this kind of thing.

**Comment by puckey** [comment] 2017-09-13 12:43
I have hundreds of pages with incorrect slugs because of this panel bug. And I don't think my editors are going to understand why they should not put numbers at the start of a page title.. (I run a radio directory and every other radio station name starts with a number)

How about the panel automatically adds a '-' in front of the directory name when someone makes a page title that starts with a number and have Kirby swallow the first '-' when generating the slug?

**Closed as completed** 2021-01-25 11:54 UTC
Labels: enhancement, idea
