### ISSUE TITLE
Allow renaming of visibility toggle on a per blueprint basis

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#708] opened 2015-12-21 12:50 UTC
See issue https://github.com/getkirby/panel/issues/706

**Comment by distantnative** [comment] 2016-02-06 14:48
Syntax suggestion – maybe also including renaming of `Files` and `Pages` in the sidebar?

```
title: Page
labels:
  pages:  Blog Posts
  files  Documents
  visible:  published
  invisible: unpublished
pages: true
files: true
```

Multi-lang:
```
labels:
  pages:  
    en: Blog Posts
    de: Beiträge
```

Thoughts?

**Comment by lukasbestle** [comment] 2016-02-06 16:08
This idea is a duplicate of #248. Bastian, Sonja and I are actually currently discussing this.

**Comment by texnixe** [comment] 2016-02-06 16:29
The question is how these customization can be done in a good way, because it's not just one label in the sidebar that needs to be changed but all occurrences in the interface, dialog boxes etc. in all languages ...

**Closed as completed** 2021-01-25 11:54 UTC
Labels: idea
