### ISSUE TITLE
`language` field in blueprint conflicts with panel language switcher on multilang sites

### ISSUE THREAD

**Issue by rasteiner** [getkirby-v2/panel#790] opened 2016-03-01 16:01 UTC
Not a major issue. But having a `language` field in a blueprint, like this:

``` yaml
   language:
    label: Language
    type: select
    options:
      de: German
      fr: French
      it: Italian
```

Unexpectedly sets that field when I change the language in the panel here: 
![image](https://cloud.githubusercontent.com/assets/6684137/13432635/c7968770-dfce-11e5-99d4-48fa549a63ca.png)

I guess that's because both (the language switcher and my field) are transmitted with the same input name. I suggest changing the language switcher input name to something more unique (like `kcpanellang` or something) to avoid conflicts.

Of course, a simple work-around is to just use another name for the blueprint field (like `lang`)

**Comment by distantnative** [comment] 2016-03-08 14:54
I cannot reproduce this. My test blueprint:

```
title: Projects
pages:
  template: project
files: false
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  language:
    label: Language
    type: select
    options:
      de: German
      fr: French
      it: Italian
```

But I still only see the two languages set up in the `config.php` in the language dropdown:
<img width="707" alt="screen shot 2016-03-08 at 15 53 57" src="https://cloud.githubusercontent.com/assets/3788865/13605060/0169fec4-e546-11e5-9bf6-8d78c50e1815.png">

**Comment by rasteiner** [comment] 2016-03-08 15:37
I didn't explain myself well. 

the language switcher changes my content when my content field is called "language":

![untitled recording](https://cloud.githubusercontent.com/assets/6684137/13606223/84bdb720-e54b-11e5-8e11-139ea76bd116.gif)

and vice-versa, saving the content sets my panel language:
![untitled recording 2](https://cloud.githubusercontent.com/assets/6684137/13606388/1628d366-e54c-11e5-8d0a-6930c79ef3be.gif)

**Comment by distantnative** [comment] 2016-03-08 16:39
Ah now I got it and could kinda reproduce it. I think it's mainly because you are using the language codes as keys for your options. Using other keys should already fix it. I am afraid the way the blueprints are set up with translations (exactly using the language codes as identifier for translations), this won't be fixed in another way that soon.

**Comment by texnixe** [comment] 2016-03-08 17:55
Or call the field something else, like "select_language" or whatever. That will also prevent other potential issues with calling the field in a template, because it might conflict with Kirby's own `language()` method (that is a general problem with all reserved words which are used by Kirby).

**Closed as completed** 2021-01-25 11:53 UTC
Labels: bug
